classDiagram
class nompers_Parameter {
}
class nompers_Family {
}
class nompers_RegionWALS {
}
class nompers_RegionGlottolog {
}
class nompers_Source {
has bibtex : xsd_string
has page : xsd_string
}
class nompers_Genus {
}
class nompers_ParameterValue {
}
class nompers_ParameterAssociation {
}
class nompers_CoreParameter {
}
class nompers_Languoid {
Glottocode : xsd_string
is terminal : xsd_boolean
}
class nompers_Language {
WALS ID : xsd_string
ISO 639-3 Code : xsd_string
}
class nompers_ControlParameter {
}
class nompers_Region {
}
class nompers_Example {
Primary Text : xsd_string
Analyzed Word : xsd_string
Gloss : xsd_string
Translation : xsd_string
}
class geo_Point {
latitude : xsd_string
longitude : xsd_string
}
nompers_Language --|> nompers_Languoid : subClassOf
nompers_Genus --|> nompers_Languoid : subClassOf
nompers_Family --|> nompers_Languoid : subClassOf
nompers_RegionGlottolog --|> nompers_Region : subClassOf
nompers_RegionWALS --|> nompers_Region : subClassOf
nompers_CoreParameter --|> nompers_Parameter : subClassOf
nompers_ControlParameter --|> nompers_Parameter : subClassOf
nompers_Languoid --> nompers_Region : in region
nompers_Language --> nompers_Genus : member of genus
nompers_Language --> nompers_Family : member of language family
nompers_Genus --> nompers_Family : is in family
nompers_Genus --> nompers_Language : has language member
nompers_Family --> nompers_Language : has family member
nompers_Family --> nompers_Genus : has genus in family
nompers_Language --> geo_Point : has coordinates
nompers_Region --> nompers_Languoid : has member
nompers_Parameter --> nompers_ParameterValue : has potential value
nompers_ParameterValue --> nompers_Parameter : is potential value of
nompers_ParameterAssociation --> nompers_Languoid : for languoid
nompers_ParameterAssociation --> nompers_Parameter : relates Parameter
nompers_ParameterAssociation --> nompers_ParameterValue : relates ParameterValue
nompers_ParameterAssociation --> nompers_Source : sourced from
nompers_Example --> nompers_Source : sourced from
nompers_ParameterAssociation --> nompers_Example : examplified by
nompers_Example --> nompers_Languoid : from Languoid